### PR TITLE
Make a python3-only release of 0.8-RC1.

### PR DESCRIPTION
**Pull request by efiring**
If/when this PR is correct, it should be preceded by removal of the 3 incorrectly labeled packages:
```
pysolar                  0.8rc1          py27_0  conda-forge
pysolar                  0.8rc1          py35_0  conda-forge
pysolar                  0.8rc1          py36_0  conda-forge
```
They are actually builds of 0.6.

### CODE REVIEW

**Comment by efiring** [comment]
I think the problem is that 0.8-RC1 is half-baked as an RC (it still has various 0.7 references internally, *and* it (wisely) switches from `import Pysolar` to `import pysolar`, so the test here fails.  It would be nice to just have a clean 0.8 release.  Could that be done, @pingswept, with minimal cleanup, even if wish-list items are left for a 0.9 release?

**Comment by efiring** [comment]
Cross-reference: PR for a version 0.8rc2: https://github.com/pingswept/pysolar/pull/87

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
@efiring we usually do the stable releases on the main channel and dev/alpha/RCs etc on a `dev` channel using a branch. Look at the last RC date we can male exception and put that in the `main` channel b/c it looks like it is "the stable one."

What do say? Are you using the RC and prefer it to be easily available on the `main`  channel? The reason I'm asking this is b/c non-main channel packages must be installed with the awkward command:

```
conda install conda-forge/label/dev::pysolar
```

**Comment by ocefpaf** [comment]
> If/when this PR is correct, it should be preceded by removal of the 3 incorrectly labeled packages:

BTW we never really remove the packages. We move than to a "broken" label.

**Comment by ocefpaf** [comment]
The CI result was not shown here for some reason but it passed:

https://circleci.com/gh/conda-forge/pysolar-feedstock/27

merging this. Thanks @efiring and @conda-forge/pysolar team!

**Comment by efiring** [comment]
@ocefpaf Thank you for all this.  The reasons I was concentrating on the 0.8RC1 are (1) it seemed to be already out there--though it turned out to be the mislabeled 0.6, (2) it is already quite old, having been tagged nearly a year ago, (3) it changes the naming relative to 0.7, so `import pysolar` replaces `import Pysolar`.  It seemed like a good idea to go with that right away.  (I was actually using pip-installed 0.7 myself, after having found the conda package to be the mislabeled 0.6, which is completely incompatible with 0.7, not to mention 0.8.)
My hope is that the PR I made for a pysolar RC2 will lead soon to a regular 0.8, at which point the conda RC1 will no longer be needed.
All this is because of one calculation I wanted to do over the weekend...

**Comment by ocefpaf** [comment]
> All this is because of one calculation I wanted to do over the weekend...

Is that how OSS evolves :smile: 

> My hope is that the PR I made for a pysolar RC2 will lead soon to a regular 0.8, at which point the conda RC1 will no longer be needed.

It is unclear to me if you need the RC in `conda-forge` or not from your message above. Note that after my modifications this PR added the `0.7` version.

We can do 0.8RC right away or wait for the 0.8 stable release, that is up to you. The only downside of the `dev` release is that we need to maintain it in a branch, and the install command is not a simple `conda install pysolar`, but rather the long and awkward `conda install conda-forge/label/dev::pysolar`.

**Comment by efiring** [comment]
This is fine.  Let's wait for a 0.8 stable before doing anything else.  (Evidently I was confused about the point at which the change in package name occurred; `import pysolar` works on 0.7.)

**Comment by ocefpaf** [comment]
Cool. BTW, the bot should send a PT for the new release automatically once it is published on GitHub.

**Pull request merged**
